name: template
channels:
- conda-forge
dependencies:
- python==3.9.2
- pip==21.0.1
- numpy==1.20.2
- scipy==1.6.2
- matplotlib==3.4.1
- numba==0.53.1
- pandas==1.2.3
- xlrd==2.0.1
- scikit-learn==0.24.1
- h5py==3.1.0
- pillow==8.1.2
- statsmodels==0.12.2
- ipympl==0.7.0
- jupyterlab==3.0.14
- joblib==1.0.1
- psutil==5.8.0
- numexpr==2.7.3
- imageio==2.9.0
- tqdm==4.60.0
- spyder-kernels==2.0.1
- imageio-ffmpeg==0.4.3
- vtk>=9.0.1
- pyvista==0.29.0
- pyvistaqt==0.3.0
- qdarkstyle==3.0.2
- darkdetect==0.3.1
- mayavi==4.7.2
- PySurfer==0.11.0
- dipy==1.4.0
- nibabel==3.2.1
- nilearn==0.7.1
- python-picard==0.4
- pyqt==5.12.3
- mne==0.23.0
- mffpy==0.6.2
- ipywidgets==7.6.3
- pip:
  - ipyvtk-simple==0.1.4
  - autoreject==0.2.1
  - mne-bids==0.7
  - pybv==0.5.0